### ISSUE TITLE
error: config file etc/core-api.yaml, error: type mismatch for field Mysql

### ISSUE THREAD

**Issue by 567MEI13** [GetcharZp/cloud-disk#1]
配置mysql的时候报这个错，是哪里没设置好吗

**Comment by GetcharZp** [comment]
核实下core-api.yml配置中是否有Mysql这个字段

**Comment by 567MEI13** [comment]
有的，是DataSource这个字段没有高亮，我看你的视频里这个字段高亮了

**Comment by GetcharZp** [comment]
检查下格式是否是yml文件的格式，缩进、冒号那些是否有问题

**Comment by 567MEI13** [comment]
万分感谢，是少了个空格

**Comment by 567MEI13** [comment]
虽然高亮了，但是还是不行
![image](https://user-images.githubusercontent.com/88084071/183281793-03ce9774-a37c-4b08-8ff5-0d9b069f77ed.png)
